### PR TITLE
Admin

### PR DESCRIPTION
**Pull request by CDacres**
Added admin boolean to users, giving override ability for project editing and deletion.
Added additional seed data for ease of testing.

Ready for review!

### CODE REVIEW

**Comment by HenrySpartGlobal** [comment]
Looks good, but we should have an indication for Admin and Users! Maybe a little avatar or Icon!?

**Comment by CDacres** [comment]
Need to add error page for incorrect user.

**Comment by CDacres** [comment]
Incorrect user now redirects to main page. Let me know what you think!

**Comment by CDacres** [comment]
Changed functionality so that rather than redirecting, links for edit and delete won't appear if you're not an admin or the project creator.

**Comment by HenrySpartGlobal** [comment]
looks good!

**Review by HenrySpartGlobal — APPROVED** [review]
All good!

**Pull request merged**
