### PR TITLE
Showcss

### PR DESCRIPTION
**Pull request by kpklein**
This is the show and index page code, ready for review.

### CODE REVIEW

**Review by ahawkins94 — APPROVED** [review]
Looks good to me

**Review by CDacres — CHANGES_REQUESTED** [review]
On the css, there's some commented out code for .show{} Can we delete it?

**Review by CDacres — APPROVED** [review]

**Comment by kpklein** [comment]
Done.

**Review by CDacres — APPROVED** [review]
Looks good, thanks Klein!

**Review by CDacres — APPROVED** [review]

**Pull request merged**
